spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers:
      - 49.50.174.195:9092
    consumer:
      # consumer bootstrap servers? ?? ???? ??
      # bootstrap-servers: 192.168.0.4:9092

      # ?? ??? Consumer Group Id
      group-id: testgroup
      # Kafka ??? ?? offset? ???, ??? ?? offset? ? ?? ???? ?? ?? ??? ??? ??
      # latest: ?? ??? ??? ???? offeset reset
      # earliest: ?? ??? ???? offeset reset
      # none: offset ??? ??? Exception ??
      auto-offset-reset: earliest
      # ???? ??? ?, key/value? ????
      # JSON ???? ??? ???? JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      # producer bootstrap servers? ?? ???? ??
      # bootstrap-servers: 3.34.97.97:9092

      # ???? ?? ?, key/value? ???
      # JSON ???? ?? ???? JsonDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
message:
  topic:
    name: test